apiVersion: v1
kind: Service
metadata:
  name: acr-api-gateway
  namespace: default
spec:
  selector:
    app: acr-api-gateway
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: acr-api-gateway
    protocol: TCP
    port: 8080
    targetPort: 8080
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-api-gateway
  namespace: default
  labels:
    app: acr-api-gateway
spec:
  selector:
    matchLabels:
      app: acr-api-gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acr-api-gateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: acr-api-gateway
        image: gcr.io/bk-acr/acr-api-gateway:latest
        resources: 
              limits:
                cpu: 500m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: acr-secret
                key: MONGODB_CONNECTION_STRING
          - name: RABBITMQ_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: acr-secret
                key: RABBITMQ_CONNECTION_STRING
          - name: JOB_ENCRYPTION_KEY
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: JOB_ENCRYPTION_KEY
          - name: AMQP_ENCRYPTION_KEY
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: AMQP_ENCRYPTION_KEY
          - name: BIND
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: BIND
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: PORT
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: DATABASE_NAME
          - name: INIT_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: acr-config
                key: INIT_ROOT_PASSWORD
    
        ports:
        - containerPort:  80
          name: acr-api-gateway
      #   volumeMounts:
      #   - name: localtime
      #     mountPath: /etc/localtime
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always